"use client";
import {useMemo,useState} from "react";
const K=.45359237,fmt=n=>Number.isFinite(Number(n))?Number(n).toLocaleString("en-US",{maximumFractionDigits:2}):"—";
const toKg=(v,u)=>{const n=Number(v);return Number.isFinite(n)?(String(u).toUpperCase()==="LB"?n*K:n):null};
const toLb=(v,u)=>{const n=Number(v);return Number.isFinite(n)?(String(u).toUpperCase()==="KG"?n/K:n):null};
export default function Home(){
 const[invoices,setInvoices]=useState([]),[report,setReport]=useState(null),[ir,setIr]=useState([]),[rr,setRr]=useState([]),[is,setIs]=useState(""),[rs,setRs]=useState(""),[busy,setBusy]=useState(false);
 const rm=useMemo(()=>new Map(rr.map(x=>[x.trackingNumber,x])),[rr]);
 const rows=useMemo(()=>ir.map(i=>{const r=rm.get(i.trackingNumber);if(!r)return{...i,status:"NOT IN REPORT"};const cu=r.reportUnit||i.invoiceUnit||"LB";const a=cu==="KG"?toKg(i.invoiceWeight,i.invoiceUnit):toLb(i.invoiceWeight,i.invoiceUnit);const b=cu==="KG"?toKg(r.reportWeight,r.reportUnit||"KG"):toLb(r.reportWeight,r.reportUnit||"LB");const d=a!=null&&b!=null?a-b:null,p=d!=null&&b>0?d/b*100:null,t=cu==="KG"?K:1;return{...i,...r,comparisonUnit:cu,normalizedInvoiceWeight:a,normalizedReportWeight:b,difference:d,differencePercent:p,status:d==null?"CHECK":d>t?"REVIEW":"OK"}}),[ir,rm]);
 async function pi(){setBusy(true);try{const f=new FormData();invoices.forEach(x=>f.append("invoices",x));const q=await fetch("/api/invoice/parse",{method:"POST",body:f}),d=await q.json();if(!q.ok||!d.ok)throw new Error(d.message);setIr(d.rows||[]);setIs(`${(d.rows||[]).length} shipment(s) extracted.`)}catch(e){setIs("ERROR: "+e.message)}finally{setBusy(false)}}
 async function pr(){setBusy(true);try{const f=new FormData();f.append("report",report);const q=await fetch("/api/report/parse",{method:"POST",body:f}),d=await q.json();if(!q.ok||!d.ok)throw new Error(d.message);setRr(d.rows||[]);setRs(`${(d.rows||[]).length} report shipment(s) loaded. Weight unit is read per shipment.`)}catch(e){setRs("ERROR: "+e.message)}finally{setBusy(false)}}
 const review=rows.filter(x=>x.status==="REVIEW").length,matched=rows.filter(x=>x.reportWeight!=null).length;
 return <main><h1>FedEx Invoice vs Shipment Report Audit</h1><p className="muted">Upload invoice PDF and FedEx report. Tracking numbers are matched automatically. If the report row is KG, invoice LB is converted to KG; if the report row is LB, invoice KG is converted to LB.</p>
 <div className="grid"><div className="card"><div className="k">Invoice shipments</div><div className="v">{ir.length}</div></div><div className="card"><div className="k">Report shipments</div><div className="v">{rr.length}</div></div><div className="card"><div className="k">Matched</div><div className="v">{matched}</div></div><div className="card"><div className="k">Needs review</div><div className="v">{review}</div></div></div>
 <section className="panel"><h2>1. Upload FedEx invoice</h2><div className="row"><div className="field"><label>Invoice PDF(s)</label><input type="file" accept=".pdf,application/pdf" multiple onChange={e=>setInvoices(Array.from(e.target.files||[]))}/></div><button className="primary" disabled={busy||!invoices.length} onClick={pi}>Parse invoice</button></div><div className="status">{is}</div></section>
 <section className="panel"><h2>2. Upload FedEx shipment report</h2><div className="row"><div className="field"><label>FedEx report CSV / XLS / XLSX</label><input type="file" accept=".csv,.xls,.xlsx" onChange={e=>setReport(e.target.files?.[0]||null)}/></div><button className="primary" disabled={busy||!report} onClick={pr}>Load report</button></div><div className="status">{rs}</div></section>
 <section className="panel"><h2>3. Comparison results</h2><div className="wrap"><table><thead><tr><th>Tracking</th><th>Invoice original</th><th>FedEx report original</th><th>Original Weight</th><th>Compare unit</th><th>Invoice normalized</th><th>FedEx normalized</th><th>Difference</th><th>Difference %</th><th>Status</th></tr></thead><tbody>{!rows.length&&<tr><td colSpan="10" className="muted">Upload both files.</td></tr>}{rows.map((r,i)=><tr key={r.trackingNumber+"-"+i}><td className="mono">{r.trackingNumber}</td><td>{r.invoiceWeight!=null?`${fmt(r.invoiceWeight)} ${r.invoiceUnit||""}`:"—"}</td><td>{r.reportWeight!=null?`${fmt(r.reportWeight)} ${r.reportUnit||""}`:"Not in report"}</td><td>{r.originalWeight!=null?`${fmt(r.originalWeight)} ${r.reportUnit||""}`:"—"}</td><td>{r.comparisonUnit||"—"}</td><td>{r.normalizedInvoiceWeight!=null?`${fmt(r.normalizedInvoiceWeight)} ${r.comparisonUnit}`:"—"}</td><td>{r.normalizedReportWeight!=null?`${fmt(r.normalizedReportWeight)} ${r.comparisonUnit}`:"—"}</td><td>{r.difference!=null?`${r.difference>=0?"+":""}${fmt(r.difference)} ${r.comparisonUnit}`:"—"}</td><td>{r.differencePercent!=null?`${r.differencePercent>=0?"+":""}${fmt(r.differencePercent)}%`:"—"}</td><td>{r.status}</td></tr>)}</tbody></table></div></section></main>
}